### ISSUE TITLE
Does it can be modified for work without toroidal power supply ?

### ISSUE THREAD

**Issue by Sercurio** [butchwarns/Eurorack_PSU#3]
Thanks for ur project mate, but i wonder if it can be works without a torodial power supply ? Just with a 12v AC power supply ?

And if it insn't why not adding the tordial to the PCB ? Because I don't understand where the tordial will be fixed ?

Thanks again !

**Comment by butchwarns** [comment]
Hi there, sorry for the late reply! Unfortunately, this PSU is designed to only work with a center-tapped transformer. This will not work with a single 12VAC supply.

Toroidal transformers usually come with a set of mounting "plates" that can be screwed into the back wall of the case, for instance. I didn't add the transformer directly to the board for reasons of size and stability. 

You can search "toroidal transformer mounting kit" on the web to see what I'm referring to. 

I can recommend [this ](https://github.com/backtail/6hp-psu) power supply for your use case. Works with a regular laptop charger, and comes as a slim module instead of a bulky PCB and transformer to mount in the case.

Hope this helps!

-Butch
